import fs from 'fs'

import { createGitlabCI } from './gitlab'
import { CIConfig, CI, CreateCIOptions } from './interfaces'

export { CIConfig, CI }

const writeConfigToFile = (
  configContents: string,
  outputFile: CreateCIOptions['outputFile'],
) => {
  const contents = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# USE UNIVERSAL-CI PACKAGE

${configContents}
`

  fs.writeFile(outputFile, contents, 'utf8', (error) => {
    if (error) {
      console.error(error)
      return process.exit(1)
    }

    console.log('Success')
    return process.exit(0)
  })
}

export const createCI = <Stages, JobNames>(
  options: CreateCIOptions<Stages, JobNames>,
) => {
  switch (options.ci) {
    case CI.GITLAB_CI:
      return writeConfigToFile(
        createGitlabCI<Stages, JobNames>(options.config),
        options.outputFile,
      )

    case CI.GITHUB_ACTIONS:
    case CI.CIRCLE_CI:
    case CI.TRAVIS_CI:
    case CI.JENKINS_CI:
      throw new Error(`We don't support this platform yet`)

    default:
      throw new Error('Please provide a valid CI platform')
  }
}
